### ISSUE TITLE
`Error:  fetch failed`

### ISSUE THREAD

**Issue by manuel3108** [stackblitz-labs/pkg.pr.new#126]
As of the last release, something seems broken, with the error mentioned above. 

<details><summary>Full errror</summary>
<p>

Error:  fetch failed
  at node:internal/deps/undici/undici:12502:[13](https://github.com/svelte-add/svelte-add/actions/runs/9722011422/job/26843503734#step:8:14)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (/home/runner/.cache/pnpm/dlx/mcohskmpkubcn3l36rssziqfz4/1906508f585-845/node_modules/.pnpm/pkg-pr-new@0.0.10/node_modules/pkg-pr-new/dist/index.js:3122:33)
  at async runCommand (/home/runner/.cache/pnpm/dlx/mcohskmpkubcn3l36rssziqfz4/1906508f585-845/node_modules/.pnpm/pkg-pr-new@0.0.10/node_modules/pkg-pr-new/dist/index.js:2196:16)
  at async runCommand (/home/runner/.cache/pnpm/dlx/mcohskmpkubcn3l36rssziqfz4/1906508f585-845/node_modules/.pnpm/pkg-pr-new@0.0.10/node_modules/pkg-pr-new/dist/index.js:2187:11)
  at async runMain (/home/runner/.cache/pnpm/dlx/mcohskmpkubcn3l36rssziqfz4/1906508f585-845/node_modules/.pnpm/pkg-pr-new@0.0.10/node_modules/pkg-pr-new/dist/index.js:2323:7) 
Error:  fetch failed
node:internal/errors:984
  const err = new Error(message);
              ^
Error: Command failed: pnpm dlx pkg-pr-new@0.0 publish --pnpm packages/core packages/ast-manipulation packages/cli packages/config packages/testing-library packages/website
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:[14](https://github.com/svelte-add/svelte-add/actions/runs/9722011422/job/26843503734#step:8:15))
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:[15](https://github.com/svelte-add/svelte-add/actions/runs/9722011422/job/26843503734#step:8:16))
    at file:///home/runner/work/svelte-add/svelte-add/scripts/get-deps-to-publish.js:39:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:3[16](https://github.com/svelte-add/svelte-add/actions/runs/9722011422/job/26843503734#step:8:17):24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2116,
  stdout: null,
  stderr: null
}
Node.js v20.15.0
Error: Process completed with exit code 1.

</p>
</details> 

This is a workflow run that worked yesterday, which I have just re-run via the github interface: https://github.com/svelte-add/svelte-add/actions/runs/9722011422/job/26843503734. 
And here is the successful run from yesterday: https://github.com/svelte-add/svelte-add/actions/runs/9722011422/attempts/1

First appeared in https://github.com/svelte-add/svelte-add/pull/446

**Comment by Aslemammad** [comment]
I'm sorry for that, just released v0.0.11, let me know if it fixes the issue!

**Comment by manuel3108** [comment]
No problem! Everything is working as expected now!

**Comment by Aslemammad** [comment]
Thank you so much
