### ISSUE TITLE
npm error when trying to publish the packages

### ISSUE THREAD

**Issue by ematipico** [stackblitz-labs/pkg.pr.new#179]
I am trying to integrate `pkg.pr.new` into another repository, but when I run the publish script, I get a weird error that I don't know how to debug: 

```
 Error:  npm pack exited with a status of 1.

npm error Cannot set properties of null (setting 'peer')

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-08-19T12_52_41_503Z-debug-0.log
  
  npm error Cannot set properties of null (setting 'peer')
  
  npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-08-19T12_52_41_503Z-debug-0.log
  at normalizeResult (/home/runner/.cache/pnpm/dlx/3dcy2udhwvnokrpfjxa7gknbfu/1916ab251b2-7bf/node_modules/.pnpm/@jsdevtools+ez-spawn@3.0.4/node_modules/@jsdevtools/ez-spawn/lib/normalize-result.js:31:11)
  at ChildProcess.<anonymous> (/home/runner/.cache/pnpm/dlx/3dcy2udhwvnokrpfjxa7gknbfu/1916ab251b2-7bf/node_modules/.pnpm/@jsdevtools+ez-spawn@3.0.4/node_modules/@jsdevtools/ez-spawn/lib/async.js:79:19)
  at ChildProcess.emit (node:events:517:28)
  at ChildProcess._handle.onexit (node:internal/child_process:292:12) 

Error:  npm pack exited with a status of 1.

npm error Cannot set properties of null (setting 'peer')

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-08-19T12_52_41_503Z-debug-0.log
Error: Process completed with exit code 1.
```

https://github.com/withastro/astro/actions/runs/10453723816/job/28944762060?pr=11768#step:8:19

**Comment by Aslemammad** [comment]
Thank you for reporting this! Can you see if `--pnpm` would solve your issue?

> pkg.pr.new uses npm pack --json under the hood, in case you face issues, you can also use the --pnpm flag so it starts using pnpm pack. This is not necessary in most cases.

**Comment by ematipico** [comment]
That works, thank you! I completely missed that part of the docs

**Comment by Aslemammad** [comment]
Happy it worked out! ❤️
