### ISSUE TITLE
Cannot extract the repository link on repo with repository url.

### ISSUE THREAD

**Issue by alvarosabu** [stackblitz-labs/pkg.pr.new#259]
Hi there, I am getting this in one of TresJS repos https://github.com/Tresjs/cientos 

The weird thing is that I made sure the `package.json` has the repository URL configured https://github.com/Tresjs/cientos/blob/a04bd727b6d3a028521be9b6a0068002ae81c758/package.json#L9-L12 so Im not sure why is not working on any of the PRs of the repo.

I have the same config on https://github.com/Tresjs/core but there it works, so not sure what I'm doing incorrectly. Help is appreciated. 

```
Error:  pkg-pr-new cannot extract the repository link from the @tresjs/cientos manifest. --compact flag requires the link to be present.
Make sure to configure the 'repository' / 'repository.url' field in its package.json properly.
See https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository for details.
  Make sure to configure the 'repository' / 'repository.url' field in its package.json properly.
  See https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository for details.
  at verifyCompactMode (/home/runner/.cache/pnpm/dlx/3dcy2udhwvnokrpfjxa7gknbfu/19256848c1f-771/node_modules/.pnpm/pkg-pr-new@0.0.29/node_modules/pkg-pr-new/dist/index.js:3502:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (/home/runner/.cache/pnpm/dlx/3dcy2udhwvnokrpfjxa7gknbfu/19256848c1f-771/node_modules/.pnpm/pkg-pr-new@0.0.29/node_modules/pkg-pr-new/dist/index.js:3199:15)
  at async runCommand (/home/runner/.cache/pnpm/dlx/3dcy2udhwvnokrpfjxa7gknbfu/19256848c1f-771/node_modules/.pnpm/pkg-pr-new@0.0.29/node_modules/pkg-pr-new/dist/index.js:2196:16)
  at async runCommand (/home/runner/.cache/pnpm/dlx/3dcy2udhwvnokrpfjxa7gknbfu/19256848c1f-771/node_modules/.pnpm/pkg-pr-new@0.0.29/node_modules/pkg-pr-new/dist/index.js:2187:11)
  at async runMain (/home/runner/.cache/pnpm/dlx/3dcy2udhwvnokrpfjxa7gknbfu/19256848c1f-771/node_modules/.pnpm/pkg-pr-new@0.0.29/node_modules/pkg-pr-new/dist/index.js:[23](https://github.com/Tresjs/cientos/actions/runs/11145292886/job/31068857934#step:7:24)23:7) 

Error:  pkg-pr-new cannot extract the repository link from the @tresjs/cientos manifest. --compact flag requires the link to be present.
Make sure to configure the 'repository' / 'repository.url' field in its package.json properly.
See https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository for details.
Error: Process completed with exit code 1.
##[debug]Finishing: Run pnpx pkg-pr-new publish --compact --pnpm
```

**Comment by Aslemammad** [comment]
Ok, I think you haven't released that!

Since the source of truth for --compact is npm, it should be there in npm. But right now, the change is not published in npm!

**Comment by alvarosabu** [comment]
OHHHH I see thanks a lot @Aslemammad makes sense, we can close this

**Comment by Aslemammad** [comment]
Thank you so much for that!
