### ISSUE TITLE
Push code release failed

### ISSUE THREAD

**Issue by ghost** [stackblitz-labs/pkg.pr.new#300]
Run `pnpx pkg-pr-new publish`

publish error

PR:       ✔️
Push:   ❌

### logs

```
Error:  publishing failed: {"url":"/publish","statusCode":403,"statusMessage":"","message":"Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment"}
  at Object.run (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/193b0ccbbac-a75/node_modules/.pnpm/pkg-pr-new@0.0.35/node_modules/pkg-pr-new/dist/index.js:3421:18)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async runCommand (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/193b0ccbbac-a75/node_modules/.pnpm/pkg-pr-new@0.0.35/node_modules/pkg-pr-new/dist/index.js:2196:[16](https://github.com/element-plus/element-plus/actions/runs/12257309026/job/34194482729#step:10:17))
  at async runCommand (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/193b0ccbbac-a75/node_modules/.pnpm/pkg-pr-new@0.0.35/node_modules/pkg-pr-new/dist/index.js:2187:11)
  at async runMain (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/193b0ccbbac-a75/node_modules/.pnpm/pkg-pr-new@0.0.35/node_modules/pkg-pr-new/dist/index.js:2323:7) 

Error:  publishing failed: {"url":"/publish","statusCode":403,"statusMessage":"","message":"Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment"}
Error: Process completed with exit code 1.
```
https://github.com/element-plus/element-plus/blob/d9da5341d2ce82e2de630fc794aef0b524beb74c/.github/workflows/publish-pr-commit-pkg.yml#L51C11-L51C34
https://github.com/element-plus/element-plus/actions/runs/12257309026/job/34194482729

**Comment by warmthsea2** [comment]
@btea 
Could you help me try it?

**Comment by btea** [comment]
> thank you for creating the issue, can you try re-running the failed workflow?

I have tried again, but still get the 403 error.

The strange thing is that the created PR can be published normally, but this error will appear after the PR is merged into the dev branch. 🤔

**Comment by btea** [comment]
> @btea Could you help me try it?

The problem still exists.

**Comment by Aslemammad** [comment]
it is so strange, i'll do something about it!

**Comment by Aslemammad** [comment]
can you try re-installing the app itself and try again with a new merge on another pr?

**Comment by Aslemammad** [comment]
the error is 403 and it's something around messed up permissions, but it also shows that previous commits/merges used to work, which makes it weird!

**Comment by btea** [comment]
yeah, we have reinstalled it and will try to merge the new PR later.

**Comment by btea** [comment]
Unfortunately, this problem still exists. https://github.com/element-plus/element-plus/actions/runs/12271320706/job/34237996910

**Comment by Aslemammad** [comment]
Ahh, i'll see again.

**Comment by Aslemammad** [comment]
which option do you choose, when merging? just asking to see if i can reproduce in the best way possible! 

![CleanShot 2024-12-11 at 1  54 00](https://github.com/user-attachments/assets/81984cd2-5adb-437f-a0af-2ed52119a69b)

**Comment by btea** [comment]
The second

![image](https://github.com/user-attachments/assets/2be3710b-df75-490b-bab4-3b594b7b9b30)

**Comment by Aslemammad** [comment]
here's my username, feel free to send a friend request: aslemammad

**Comment by posva** [comment]
I think you need the PR to be opened by an external person, then squash merge. This happened to me a few times: https://github.com/posva/unplugin-vue-router/actions/runs/12883975525/job/35919305398

**Comment by Aslemammad** [comment]
oh i see 
i will look into it again, thank you so much for the insights!

**Comment by Aslemammad** [comment]
will release soon and see if it fixes the issue!

**Comment by warmthsea** [comment]
> Turning off comments with `--comment=off` fixed it but no more comment 🥲

I tried it after seeing your comment. when pushing, I set `--comment=off`, which indeed solved the problem. thanks!

- https://github.com/element-plus/element-plus/pull/19922/files

![Image](https://github.com/user-attachments/assets/fa398d94-fc23-461d-acbb-57452518db7b)

**Comment by Aslemammad** [comment]
we made a release y'all!

**Comment by Aslemammad** [comment]
i appreciate you!
